# Generated by Django 3.0.2 on 2020-11-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='img',
            field=models.ImageField(null=True, upload_to='events_imgs'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(null=True, upload_to='gallery_imgs'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='img',
            field=models.ImageField(null=True, upload_to='mentor_imgs'),
        ),
    ]
